// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOwGePUo4cAHfkftdmXMKchzlqn9PDg2s',
    appId: '1:570598263087:web:a7ca5950dac07a0c4d79da',
    messagingSenderId: '570598263087',
    projectId: 'syn-clights',
    authDomain: 'syn-clights.firebaseapp.com',
    storageBucket: 'syn-clights.appspot.com',
    measurementId: 'G-JNQ50B5JL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGM4jxgA4A7kLEvGXa5I7pafjt8AfJQvw',
    appId: '1:570598263087:android:fb0e18cf5d8da1124d79da',
    messagingSenderId: '570598263087',
    projectId: 'syn-clights',
    storageBucket: 'syn-clights.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfZhIRb-r78lUDgDWyAIAYRhvp5QBVlyc',
    appId: '1:570598263087:ios:7606446f4d3f30cc4d79da',
    messagingSenderId: '570598263087',
    projectId: 'syn-clights',
    storageBucket: 'syn-clights.appspot.com',
    iosClientId: '570598263087-8vstmf6s1foc8fbadqolpsfr18be1qoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.synclights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfZhIRb-r78lUDgDWyAIAYRhvp5QBVlyc',
    appId: '1:570598263087:ios:7606446f4d3f30cc4d79da',
    messagingSenderId: '570598263087',
    projectId: 'syn-clights',
    storageBucket: 'syn-clights.appspot.com',
    iosClientId: '570598263087-8vstmf6s1foc8fbadqolpsfr18be1qoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.synclights',
  );
}
