name: Android Build Release
on:
  push:
    branches: ["FlutterFrontEnd"]
  pull_request:
    branches: ["FlutterFrontEnd"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: "stable"
      - name: Flutter Update
        run: flutter upgrade
          
      - name: Get dependencies
        continue-on-error: true
        run: flutter pub get
   
      - name: Remove Apks
        continue-on-error: true
        run: rm -r build

      - name: Start release build
        run: flutter build apk